import type { Metadata } from "next";
import localFont from "next/font/local";
import "../globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbar";
import { Footer } from "@/components/Footer";
import { nuckleRegular, nuckleMedium } from "../../lib/fonts";

export const metadata: Metadata = {
  title: "DAVRILSUPPLY",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" className="h-full">
      <body
        className={cn(
          "relative h-full antialiased",
          nuckleRegular.className        
        )}
      >
        <main className="relative flex flex-col min-h-screen">
          <Navbar />
          <div className={cn("flex-grow flex-1", nuckleMedium.className)}>{children}</div>
        </main>
        <Footer />
      </body>
    </html>
  );
}
